# Generated by Django 5.2 on 2025-05-13 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, null=True)),
                ('number', models.IntegerField(null=True)),
                ('zip', models.IntegerField(null=True)),
                ('city', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CONTINGENT', 'Contingent')], max_length=20, null=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('HOUSE', 'House'), ('CONDO', 'Condo'), ('TOWNHOME', 'Townhome'), ('MULTIFAMILY', 'Multifamily'), ('MOBILE', 'Mobile'), ('FARM', 'Farm'), ('LAND', 'Land'), ('COMMERCIAL', 'Commercial')], default='HOUSE', max_length=20)),
                ('price', models.FloatField(null=True)),
                ('listing_date', models.DateField(default=django.utils.timezone.now)),
                ('numb_of_rooms', models.IntegerField(null=True)),
                ('bath_rooms', models.IntegerField(null=True)),
                ('bed_rooms', models.IntegerField(null=True)),
                ('size_sqm', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CONTINGENT', 'Contingent')], default='PENDING', max_length=20)),
                ('thumbnail', models.CharField(blank=True, max_length=4096)),
                ('seller_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='Sellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=4096)),
                ('thumbnail', models.BooleanField(default=False)),
                ('listing_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Listings.listing')),
            ],
        ),
    ]
