# Generated by Django 5.2 on 2025-05-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('NEW_YORK', 'New York'), ('LOS_ANGELES', 'Los Angeles'), ('LONDON', 'London'), ('PARIS', 'Paris'), ('BERLIN', 'Berlin'), ('TOKYO', 'Tokyo'), ('SEOUL', 'Seoul'), ('SHANGHAI', 'Shanghai'), ('BEIJING', 'Beijing'), ('MUMBAI', 'Mumbai'), ('DELHI', 'Delhi'), ('SYDNEY', 'Sydney'), ('TORONTO', 'Toronto'), ('VANCOUVER', 'Vancouver'), ('RIO_DE_JANEIRO', 'Rio de Janeiro'), ('MEXICO_CITY', 'Mexico City'), ('DUBAI', 'Dubai'), ('SINGAPORE', 'Singapore'), ('MOSCOW', 'Moscow'), ('JOHANNESBURG', 'Johannesburg'), ('REYKJAVIK', 'Reykjavík'), ('ROME', 'Rome'), ('BARCELONA', 'Barcelona'), ('AMSTERDAM', 'Amsterdam'), ('BANGKOK', 'Bangkok'), ('HONG_KONG', 'Hong Kong'), ('CHICAGO', 'Chicago'), ('SAN_FRANCISCO', 'San Francisco'), ('MIAMI', 'Miami'), ('CAIRO', 'Cairo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Pending'), ('SOLD', 'Sold'), ('EXPIRED', 'Expired'), ('DELETED', 'Deleted')], default='AVAILABLE', max_length=20),
        ),
    ]
