# Generated by Django 5.2 on 2025-05-08 11:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='numb_of_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='size_sqm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CONTINGENT', 'Contingent')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('CONDO', 'Condo'), ('TOWNHOME', 'Townhome'), ('MULTIFAMILY', 'Multifamily'), ('MOBILE', 'Mobile'), ('FARM', 'Farm'), ('LAND', 'Land'), ('COMMERCIAL', 'Commercial')], default='HOUSE', max_length=20),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Listings.listing'),
        ),
    ]
