# Generated by Django 5.2 on 2025-05-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0002_alter_listing_city_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
