# Generated by Django 5.2 on 2025-05-08 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0002_listing_description_listing_listing_date_and_more'),
        ('Sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='seller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Sellers.seller'),
        ),
    ]
