# Generated by Django 5.2 on 2025-05-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0003_listing_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bath_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='bed_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CONTINGENT', 'Contingent')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='zip',
            field=models.IntegerField(null=True),
        ),
    ]
