# Generated by Django 5.2 on 2025-05-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0003_alter_listing_thumbnail_alter_listingimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=4900, null=True),
        ),
    ]
