# Generated by Django 5.2 on 2025-05-09 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0004_listing_bath_rooms_listing_bed_rooms_listing_city_and_more'),
        ('Sellers', '0002_remove_seller_profile_image_seller_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='seller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='Sellers.seller'),
        ),
    ]
