# Generated by Django 5.2 on 2025-05-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0005_alter_listing_seller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='listing',
            new_name='listing_id',
        ),
    ]
