# Generated by Django 5.2 on 2025-05-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0006_rename_listing_listingimage_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
