# Generated by Django 5.2 on 2025-05-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='seller_profiles/')),
                ('seller_type', models.CharField(choices=[('Individual', 'Individual'), ('Agency', 'Real Estate Agency')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='seller_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='seller_cover_images/')),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
