# Generated by Django 5.2 on 2025-05-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='seller',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
