# Generated by Django 5.2 on 2025-05-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sellers', '0002_remove_seller_profile_image_seller_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='address',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='seller',
            name='house_numb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
