# Generated by Django 5.2 on 2025-05-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sellers', '0002_seller_country_seller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='profile_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
