# Generated by Django 5.2 on 2025-05-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sellers', '0004_alter_seller_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=4900, null=True),
        ),
    ]
