# Generated by Django 5.2 on 2025-05-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('profile_image_url', models.CharField(blank=True, max_length=4096)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('house_numb', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
