# Generated by Django 5.2 on 2025-05-14 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='country',
            field=models.CharField(choices=[('UNITED_STATES', 'United States'), ('CANADA', 'Canada'), ('UNITED_KINGDOM', 'United Kingdom'), ('GERMANY', 'Germany'), ('FRANCE', 'France'), ('ITALY', 'Italy'), ('SPAIN', 'Spain'), ('NETHERLANDS', 'Netherlands'), ('SWEDEN', 'Sweden'), ('NORWAY', 'Norway'), ('DENMARK', 'Denmark'), ('ICELAND', 'Iceland'), ('AUSTRALIA', 'Australia'), ('NEW_ZEALAND', 'New Zealand'), ('JAPAN', 'Japan'), ('SOUTH_KOREA', 'South Korea'), ('CHINA', 'China'), ('INDIA', 'India'), ('BRAZIL', 'Brazil'), ('MEXICO', 'Mexico'), ('RUSSIA', 'Russia'), ('SOUTH_AFRICA', 'South Africa'), ('UNITED_ARAB_EMIRATES', 'United Arab Emirates'), ('SINGAPORE', 'Singapore')], default='ICELAND', max_length=30),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
