# Generated by Django 5.2 on 2025-05-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='buyer_profiles/'),
        ),
    ]
