# Generated by Django 5.2 on 2025-05-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='address',
            new_name='house_numb',
        ),
        migrations.AddField(
            model_name='buyer',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
