# Generated by Django 5.2 on 2025-05-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyers', '0002_buyer_user_alter_buyer_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='profile_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
