# Generated by Django 5.2 on 2025-05-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyers', '0002_rename_address_buyer_house_numb_buyer_street_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='street_name',
        ),
        migrations.AddField(
            model_name='buyer',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
