# Generated by Django 5.2 on 2025-05-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyers', '0004_alter_buyer_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='profile_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
