# Generated by Django 5.2 on 2025-05-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyers', '0005_alter_buyer_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
