# Generated by Django 5.2 on 2025-05-13 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Buyers', '0001_initial'),
        ('Listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('submission_date', models.DateField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CONTINGENT', 'Contingent')], default='PENDING', max_length=20)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Buyers.buyer')),
                ('property_listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Listings.listing')),
            ],
        ),
    ]
