# Generated by Django 5.2 on 2025-05-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CONTINGENT', 'Contingent'), ('BOUGHT', 'Bought')], default='PENDING', max_length=20),
        ),
    ]
