# Generated by Django 5.2 on 2025-05-08 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0002_listing_description_listing_listing_date_and_more'),
        ('Offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='property_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Listings.listing'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
