# Generated by Django 5.2 on 2025-05-13 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_street', models.CharField(max_length=255)),
                ('contact_house_number', models.IntegerField()),
                ('contact_zip', models.IntegerField()),
                ('contact_country', models.CharField(choices=[('UNITED_STATES', 'United States'), ('CANADA', 'Canada'), ('UNITED_KINGDOM', 'United Kingdom'), ('GERMANY', 'Germany'), ('FRANCE', 'France'), ('ITALY', 'Italy'), ('SPAIN', 'Spain'), ('NETHERLANDS', 'Netherlands'), ('SWEDEN', 'Sweden'), ('NORWAY', 'Norway'), ('DENMARK', 'Denmark'), ('ICELAND', 'Iceland'), ('AUSTRALIA', 'Australia'), ('NEW_ZEALAND', 'New Zealand'), ('JAPAN', 'Japan'), ('SOUTH_KOREA', 'South Korea'), ('CHINA', 'China'), ('INDIA', 'India'), ('BRAZIL', 'Brazil'), ('MEXICO', 'Mexico'), ('RUSSIA', 'Russia'), ('SOUTH_AFRICA', 'South Africa'), ('UNITED_ARAB_EMIRATES', 'United Arab Emirates'), ('SINGAPORE', 'Singapore')], max_length=30)),
                ('contact_SSN', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodMortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mortgage_provider', models.CharField(max_length=255)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionM', to='Transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodCreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=16)),
                ('expiry_date', models.DateField()),
                ('CVC', models.CharField(max_length=4)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionCC', to='Transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodBankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.CharField(max_length=17)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionBT', to='Transactions.transaction')),
            ],
        ),
    ]
