# Generated by Django 5.2 on 2025-05-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_transaction_offer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethodcreditcard',
            name='expiry_date',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
