# Generated by Django 5.2 on 2025-05-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_alter_paymentmethodcreditcard_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethodcreditcard',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
