# Generated by Django 5.2 on 2025-05-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0005_alter_paymentmethodcreditcard_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethodbanktransfer',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='paymentmethodcreditcard',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='paymentmethodmortgage',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='offer_id',
            new_name='offer',
        ),
    ]
