# Generated by Django 5.2 on 2025-05-15 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0001_initial'),
        ('Transactions', '0006_rename_transaction_id_paymentmethodbanktransfer_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='Offers.offer'),
        ),
    ]
