# Generated by Django 5.2 on 2025-05-15 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0001_initial'),
        ('Transactions', '0007_alter_transaction_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethodbanktransfer',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transactionBT', to='Offers.offer'),
        ),
        migrations.AlterField(
            model_name='paymentmethodcreditcard',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transactionCC', to='Offers.offer'),
        ),
        migrations.AlterField(
            model_name='paymentmethodmortgage',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transactionM', to='Offers.offer'),
        ),
    ]
