# Generated by Django 5.2 on 2025-05-15 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0008_alter_paymentmethodbanktransfer_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethodbanktransfer',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transactionBT', to='Transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='paymentmethodcreditcard',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transactionCC', to='Transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='paymentmethodmortgage',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transactionM', to='Transactions.transaction'),
        ),
    ]
