# Generated by Django 5.2 on 2025-05-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0009_alter_paymentmethodbanktransfer_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
