# Generated by Django 5.2 on 2025-05-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0010_transaction_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contact_city',
            field=models.CharField(choices=[('NEW_YORK', 'New York'), ('LOS_ANGELES', 'Los Angeles'), ('LONDON', 'London'), ('PARIS', 'Paris'), ('BERLIN', 'Berlin'), ('TOKYO', 'Tokyo'), ('SEOUL', 'Seoul'), ('SHANGHAI', 'Shanghai'), ('BEIJING', 'Beijing'), ('MUMBAI', 'Mumbai'), ('DELHI', 'Delhi'), ('SYDNEY', 'Sydney'), ('TORONTO', 'Toronto'), ('VANCOUVER', 'Vancouver'), ('RIO_DE_JANEIRO', 'Rio de Janeiro'), ('MEXICO_CITY', 'Mexico City'), ('DUBAI', 'Dubai'), ('SINGAPORE', 'Singapore'), ('MOSCOW', 'Moscow'), ('JOHANNESBURG', 'Johannesburg'), ('REYKJAVIK', 'Reykjavík'), ('ROME', 'Rome'), ('BARCELONA', 'Barcelona'), ('AMSTERDAM', 'Amsterdam'), ('BANGKOK', 'Bangkok'), ('HONG_KONG', 'Hong Kong'), ('CHICAGO', 'Chicago'), ('SAN_FRANCISCO', 'San Francisco'), ('MIAMI', 'Miami'), ('CAIRO', 'Cairo')], default='GERMANY', max_length=30),
            preserve_default=False,
        ),
    ]
